//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyenvanhuynh_2210900031.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public string GuestID { get; set; }
        public string SessionID { get; set; }
        public Nullable<System.DateTime> VisitTime { get; set; }
        public string VisitProduct { get; set; }
    }
}
