//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyenvanhuynh_2210900031.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public string ReviewID { get; set; }
        public string MemberID { get; set; }
        public string ProductID { get; set; }
        public Nullable<byte> Rating { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
    }
}
